### PR TITLE
Remove usage of I/You/We/They and Your issue (#9)

### PR DESCRIPTION
**Pull request by murindwaz**
Rewording and re-organization of phrases, in a way the above adverbs are not necessary.

### CODE REVIEW

**Comment by hueitan** [comment]
:tada: @murindwaz many thanks to your contribution. 
I would like to have it stay for a while before merging this pr.

Good work!

**Comment by murindwaz** [comment]
> 🎉 @murindwaz many thanks to your contribution.
> I would like to have it stay for a while before merging this pr.
> 
> Good work!

No Problem! Thanks -- you did a good work putting this thing together ;-)

**Comment by hueitan** [comment]
Thanks again, this is super helpful! @murindwaz

**Comment by murindwaz** [comment]
@hueitan You are welcome. I guess we can close issue #9  then.

**Comment by hueitan** [comment]
@all-contributors please add @murindwaz  for documentation

**Pull request merged**
